name: di-make-mkc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-14, macos-15, macos-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        math: [DI_INTERNAL, DI_GMP, DI_MPDECIMAL, DI_TOMMATH]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl
          - os: macos-15-intel, macos-14, macos-15, macos-latest
            math: DI_TOMMATH

    steps:
      - uses: actions/checkout@v4

      - name: Install Packages
        shell: bash
        run: |
          if [[ $RUNNER_OS == Linux ]]; then
            sudo apt -y update
            sudo apt -y install mpdecimal libtommath
          fi

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "inst-dir=${{ runner.temp }}/di-install" >> "$GITHUB_OUTPUT"

      - name: Configure / Build
        run: >
          make PREFIX=${{ steps.strings.outputs.inst-dir }}
          DI_USE_MATH=${{ matrix.math }}
          CC=${{ matrix.c_compiler }}
          mkc-all

      - name: Test
        run: >
          make PREFIX=${{ steps.strings.outputs.inst-dir }}
          CC=${{ matrix.c_compiler }}
          mkc-test

      - name: Install
        run: >
          make PREFIX=${{ steps.strings.outputs.inst-dir }}
          CC=${{ matrix.c_compiler }}
          mkc-install
